export const colorList = [
  {"zh_CN":"绯红","en_US":"Crimson","color":"#dc4437","name":"Crimson"},
  {"zh_CN":"石榴红","en_US":"Pomegranate Red","color":"#C7666E","name":"PomegranateRed"},
  {"zh_CN":"桔橙爆裂","en_US":"Tangerine Burst","color":"#f15a23","name":"TangerineBurst"},
  {"zh_CN":"摩卡棕","en_US":"Mocha Brown","color":"#856b5a","name":"MochaBrown"},
  {"zh_CN":"深褐","en_US":"Dark Brown","color":"#654321","name":"DarkBrown"},
  {"zh_CN":"火焰橙","en_US":"Flame Orange","color":"#ff9700","name":"FlameOrange"},
  {"zh_CN":"金色光芒","en_US":"Golden Glow","color":"#fdc844","name":"GoldenGlow"},
  {"zh_CN":"桂花黄","en_US":"Osmanthus Yellow","color":"#f9b300","name":"OsmanthusYellow"},
  {"zh_CN":"柠檬黄","en_US":"Lemon Yellow","color":"#fdd72d","name":"LemonYellow"},
  {"zh_CN":"草原绿","en_US":"Prairie Green","color":"#86bc52","name":"PrairieGreen"},
  {"zh_CN":"活力青柠","en_US":"Lively Lime","color":"#a7e278","name":"LivelyLime"},
  {"zh_CN":"翡翠绿","en_US":"Jade Green","color":"#109d57","name":"JadeGreen"},
  {"zh_CN":"翠绿丛林","en_US":"Emerald Jungle","color":"#1b8457","name":"EmeraldJungle"},
  {"zh_CN":"雨后清新","en_US":"Fresh After Rain","color":"#73c8a9","name":"FreshAfterRain"},
  {"zh_CN":"薄荷清新","en_US":"Fresh Mint","color":"#48cfae","name":"FreshMint"},
  {"zh_CN":"碧蓝海岸","en_US":"Azure Coast","color":"#00a6ac","name":"AzureCoast"},
  {"zh_CN":"海浪蓝","en_US":"Sea Blue","color":"#4f42b5","name":"SeaBlue"},
  {"zh_CN":"蔚蓝微风","en_US":"Azure Breeze","color":"#4fc0e8","name":"AzureBreeze"},
  {"zh_CN":"石板灰","en_US":"Slate Gray","color":"#607d8b","name":"SlateGray"},
  {"zh_CN":"宝石蓝","en_US":"Sapphire Blue","color":"#3e7cf3","name":"SapphireBlue"},
  {"zh_CN":"薰衣草","en_US":"Lavender","color":"#ac92ed","name":"Lavender"},
  {"zh_CN":"皇家紫","en_US":"Royal Purple","color":"#6950a1","name":"RoyalPurple"},
  {"zh_CN":"清雅紫","en_US":"Elegant Purple","color":"#ae81ff","name":"ElegantPurple"},
  {"zh_CN":"紫罗兰","en_US":"Violet","color":"#8f50b5","name":"Violet"},
  {"zh_CN":"棉花糖","en_US":"Cotton Candy","color":"#f7c2d2","name":"CottonCandy"},
  {"zh_CN":"玫瑰石英","en_US":"Rose Quartz","color":"#fa7298","name":"RoseQuartz"},
  {"zh_CN":"桃粉色","en_US":"Peach Pink","color":"#f391a8","name":"PeachPink"},
  {"zh_CN":"桃红","en_US":"Peach Red","color":"#f55b77","name":"PeachRed"}
]